#!/bin/bash


toilet "Привет бомжи"
# if [ [$n == "--help"] ]; 
# then echo "HELP\n To start n node pass arg -n <count of nodes>"
# fi
 checkD='^[0-9]+$'
if ! [[ $1 =~ $checkD ]] ; then
   echo "error: Not a number" >&2; exit 1
fi
minikube start --nodes $1 -p node